using UnityEngine;
using UnityEditor;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Net.Http;
using System.Threading.Tasks;
using EnumCollection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

/// <summary>
/// 밸런스 시뮬레이터용 데이터 JSON 추출 도구
/// Unity Editor 메뉴: Tools > Balance > Export Balance Data
/// </summary>
public class BalanceDataExporter : EditorWindow
{
    private static readonly string ExportPath = "Assets/09.Documentation/Planning/balance_data.json";
    
    // Unity Remote Config API 설정
    private const string ProjectId = "2e05c7c9-f944-4980-845d-cbb6062958db";
    private const string EnvironmentId = "c42a4d80-7e4e-4680-94f2-e10cbdee0f72"; // develop (has all keys)
    private const string AuthHeader = "Basic MTQ3NzAwMDktNWM4Mi00NzA0LTg4N2YtNDI5M2Y5MWEyOWJkOmRDRm1OanpDOFJCODJWRkhnYUktNFZtRjllSm5hSDUw";

    [MenuItem("Tools/Balance/Export Balance Data")]
    public static async void ExportBalanceData()
    {
        EditorUtility.DisplayProgressBar("Balance Export", "Remote Config 가져오는 중...", 0.1f);
        
        // Remote Config 가져오기
        var remoteConfig = await FetchRemoteConfig();
        
        EditorUtility.DisplayProgressBar("Balance Export", "에셋 데이터 추출 중...", 0.5f);
        
        var data = new BalanceData
        {
            weapons = ExportWeapons(),
            skills = ExportSkills(),
            stages = ExportStages(),
            skillAcquire = ExportSkillAcquire(),
            weaponBooks = ExportWeaponBooks(),
            remoteConfig = remoteConfig
        };

        string json = JsonConvert.SerializeObject(data, Formatting.Indented);
        File.WriteAllText(ExportPath, json, Encoding.UTF8);
        
        // JS 파일로도 저장 (file:// 에서 CORS 우회용)
        string jsPath = ExportPath.Replace(".json", ".js");
        string jsContent = $"// Auto-generated by BalanceDataExporter\nconst BALANCE_DATA_INLINE = {json};";
        File.WriteAllText(jsPath, jsContent, Encoding.UTF8);
        
        AssetDatabase.Refresh();
        
        EditorUtility.ClearProgressBar();

        Debug.Log($"[Balance Exporter] 데이터 추출 완료: {ExportPath}");
        Debug.Log($"  - 무기: {data.weapons.Count}개");
        Debug.Log($"  - 스킬: {data.skills.Count}개");
        Debug.Log($"  - 스테이지: {data.stages.Count}개");
        Debug.Log($"  - 스킬 해금: {data.skillAcquire.Count}개");
        Debug.Log($"  - 무기 도감: {data.weaponBooks.Count}개");
        Debug.Log($"  - Remote Config: {(remoteConfig != null ? "성공" : "실패")}");

        EditorUtility.DisplayDialog("Balance Data Export",
            $"데이터 추출 완료!\n\n" +
            $"무기: {data.weapons.Count}개\n" +
            $"스킬: {data.skills.Count}개\n" +
            $"스테이지: {data.stages.Count}개\n" +
            $"스킬 해금: {data.skillAcquire.Count}개\n" +
            $"무기 도감: {data.weaponBooks.Count}개\n" +
            $"Remote Config: {(remoteConfig != null ? "성공" : "실패")}\n\n" +
            $"저장 위치: {ExportPath}", "확인");
    }

    /// <summary>
    /// Unity Remote Config REST API에서 설정값 가져오기
    /// </summary>
    private static async Task<RemoteConfigExport> FetchRemoteConfig()
    {
        try
        {
            using var client = new HttpClient();
            client.DefaultRequestHeaders.Add("Authorization", AuthHeader);
            
            string url = $"https://services.api.unity.com/remote-config/v1/projects/{ProjectId}/environments/{EnvironmentId}/configs";
            
            var response = await client.GetAsync(url);
            
            if (!response.IsSuccessStatusCode)
            {
                Debug.LogWarning($"[Balance Exporter] Remote Config fetch 실패: {response.StatusCode}");
                return GetDefaultRemoteConfig();
            }

            string jsonResponse = await response.Content.ReadAsStringAsync();
            var configsArray = JObject.Parse(jsonResponse)["configs"] as JArray;
            
            if (configsArray == null || configsArray.Count == 0)
            {
                Debug.LogWarning("[Balance Exporter] Remote Config에 설정이 없습니다.");
                return GetDefaultRemoteConfig();
            }

            // 첫 번째 config의 value들 파싱
            var configValues = configsArray[0]["value"] as JArray;
            var result = new RemoteConfigExport();
            
            foreach (var item in configValues)
            {
                string key = item["key"]?.ToString();
                string value = item["value"]?.ToString();
                
                switch (key)
                {
                    case "REINFORCE_VALUE_GOLD":
                        var reinforceDict = JsonConvert.DeserializeObject<Dictionary<string, ReinforceRule>>(value);
                        if (reinforceDict.TryGetValue("Power", out var power)) result.reinforcePower = power;
                        if (reinforceDict.TryGetValue("MaxHp", out var maxHp)) result.reinforceMaxHp = maxHp;
                        if (reinforceDict.TryGetValue("CritDmg", out var critDmg)) result.reinforceCritDmg = critDmg;
                        break;
                    case "GOLD_DROP_FORMULA":
                        result.goldDropFormula = value;
                        break;
                    case "EXP_DROP_FORMULA":
                        result.expDropFormula = value;
                        break;
                }
            }
            
            // 승급 기본값 (Remote Config에 없으면)
            result.promoteRanks = result.promoteRanks ?? new PromoteInfo[]
            {
                new PromoteInfo { rank = "Stone", mult = 1f, unlockStage = 1 },
                new PromoteInfo { rank = "Bronze", mult = 1.5f, unlockStage = 30 },
                new PromoteInfo { rank = "Iron", mult = 3f, unlockStage = 60 },
                new PromoteInfo { rank = "Silver", mult = 8f, unlockStage = 120 },
                new PromoteInfo { rank = "Gold", mult = 15f, unlockStage = 200 }
            };

            Debug.Log("[Balance Exporter] Remote Config 가져오기 성공!");
            return result;
        }
        catch (System.Exception e)
        {
            Debug.LogError($"[Balance Exporter] Remote Config 오류: {e.Message}");
            return GetDefaultRemoteConfig();
        }
    }

    private static RemoteConfigExport GetDefaultRemoteConfig()
    {
        return new RemoteConfigExport
        {
            reinforcePower = new ReinforceRule { baseInc = 1f, step = 100, stepInc = 0.5f, startValue = 10f },
            reinforceMaxHp = new ReinforceRule { baseInc = 4f, step = 100, stepInc = 1f, startValue = 100f },
            reinforceCritDmg = new ReinforceRule { baseInc = 0.01f, step = 100, stepInc = 0.01f, startValue = 1.2f },
            goldDropFormula = "",
            expDropFormula = "",
            promoteRanks = new PromoteInfo[]
            {
                new PromoteInfo { rank = "Stone", mult = 1f, unlockStage = 1 },
                new PromoteInfo { rank = "Bronze", mult = 1.5f, unlockStage = 30 },
                new PromoteInfo { rank = "Iron", mult = 3f, unlockStage = 60 },
                new PromoteInfo { rank = "Silver", mult = 8f, unlockStage = 120 },
                new PromoteInfo { rank = "Gold", mult = 15f, unlockStage = 200 }
            }
        };
    }

    private static List<WeaponExport> ExportWeapons()
    {
        var list = new List<WeaponExport>();
        string[] guids = AssetDatabase.FindAssets("t:WeaponData");

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            WeaponData weapon = AssetDatabase.LoadAssetAtPath<WeaponData>(path);
            if (weapon == null) continue;

            // 무기 효과 변환
            var effects = new List<WeaponEffectExport>();
            if (weapon._weaponEffects != null)
            {
                foreach (var eff in weapon._weaponEffects)
                {
                    effects.Add(new WeaponEffectExport { skillType = (int)eff.type, skillTypeName = eff.type.ToString(), value = eff.value });
                }
            }
            
            list.Add(new WeaponExport
            {
                id = weapon.name,
                name = weapon.WeaponName,
                type = weapon.WeaponType.ToString(),
                rarity = weapon.WeaponRarity.ToString(),
                power = weapon.Power,
                critDamage = weapon.CriticalDamage,
                critical = weapon.Critical,
                attackSpeed = weapon.AttackSpeed,
                powerPerUpgrade = weapon.PowerPerUpgrade,
                critDmgPerUpgrade = weapon.CritDmgPerUpgrade,
                effects = effects
            });
        }

        return list;
    }

    private static List<SkillExport> ExportSkills()
    {
        var list = new List<SkillExport>();
        string[] guids = AssetDatabase.FindAssets("t:SkillData");

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            SkillData skill = AssetDatabase.LoadAssetAtPath<SkillData>(path);
            if (skill == null) continue;

            list.Add(new SkillExport
            {
                id = skill.name,
                name = skill.skillName,
                type = skill.type.ToString(),
                rarity = skill.rarity.ToString(),
                isActive = skill.isActiveSkill,
                isPlayerSkill = skill.isPlayerSkill,
                cooltime = skill.cooltime,
                requireMp = skill.requireMp,
                values = skill.value.ToArray()
            });
        }

        return list;
    }

    private static List<StageExport> ExportStages()
    {
        var list = new List<StageExport>();
        string[] guids = AssetDatabase.FindAssets("t:StageInfo");

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            StageInfo stage = AssetDatabase.LoadAssetAtPath<StageInfo>(path);
            if (stage == null) continue;

            list.Add(new StageExport
            {
                stageNum = stage.stageNum,
                name = stage.stageName,
                battleType = stage.battleType.ToString(),
                recommendLevel = stage.recommendLevel,
                enemyMaxHp = stage.enemyStatusFromStage?.maxHp ?? "",
                bossMaxHp = stage.bossStatusFromStage?.maxHp ?? "",
                bossResist = stage.bossStatusFromStage?.resist ?? 0f,
                bossPower = stage.bossStatusFromStage?.power ?? ""
            });
        }

        return list;
    }

    private static List<SkillAcquireExport> ExportSkillAcquire()
    {
        var list = new List<SkillAcquireExport>();
        string[] guids = AssetDatabase.FindAssets("t:SkillAcquireInfo");

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            SkillAcquireInfo info = AssetDatabase.LoadAssetAtPath<SkillAcquireInfo>(path);
            if (info == null) continue;

            list.Add(new SkillAcquireExport
            {
                acquireLevel = info.acquireLevel,
                activeSkill = info.activeSkill != null ? info.activeSkill.name : "",
                passiveSkill = info.passiveSkill != null ? info.passiveSkill.name : ""
            });
        }

        return list;
    }

    // ===== Export Data Classes =====

    [System.Serializable]
    public class BalanceData
    {
        public List<WeaponExport> weapons;
        public List<SkillExport> skills;
        public List<StageExport> stages;
        public List<SkillAcquireExport> skillAcquire;
        public List<WeaponBookExport> weaponBooks;
        public RemoteConfigExport remoteConfig;
    }

    [System.Serializable]
    public class RemoteConfigExport
    {
        // 강화 공식
        public ReinforceRule reinforcePower;
        public ReinforceRule reinforceMaxHp;
        public ReinforceRule reinforceCritDmg;
        
        // 골드/EXP 드랍 공식 (스테이지 기반)
        public string goldDropFormula;
        public string expDropFormula;
        
        // 승급 배율
        public PromoteInfo[] promoteRanks;
    }

    [System.Serializable]
    public class ReinforceRule
    {
        public float baseInc;
        public int step;
        public float stepInc;
        public float startValue;
    }

    [System.Serializable]
    public class PromoteInfo
    {
        public string rank;
        public float mult;
        public int unlockStage;
    }

    [System.Serializable]
    public class WeaponExport
    {
        public string id;
        public string name;
        public string type;
        public string rarity;
        public int power;
        public int critDamage;
        public int critical;
        public float attackSpeed;
        public int powerPerUpgrade;
        public int critDmgPerUpgrade;
        public List<WeaponEffectExport> effects;
    }

    [System.Serializable]
    public class WeaponEffectExport
    {
        public int skillType;      // SkillType enum index
        public string skillTypeName; // SkillType name for readability
        public float value;
    }

    [System.Serializable]
    public class SkillExport
    {
        public string id;
        public string name;
        public string type;
        public string rarity;
        public bool isActive;
        public bool isPlayerSkill;
        public float cooltime;
        public int requireMp;
        public float[] values;
    }

    [System.Serializable]
    public class StageExport
    {
        public int stageNum;
        public string name;
        public string battleType;
        public int recommendLevel;
        public string enemyMaxHp;
        public string bossMaxHp;
        public float bossResist;
        public string bossPower;
    }

    [System.Serializable]
    public class SkillAcquireExport
    {
        public int acquireLevel;
        public string activeSkill;
        public string passiveSkill;
    }

    [System.Serializable]
    public class WeaponBookExport
    {
        public string bookId;
        public string[] weaponIds;
        public int[] upgradeLevels;   // 각 단계별 필요 등록 무기 수
        public float[] upgradeStats;  // 각 단계별 Power 보너스
    }

    private static List<WeaponBookExport> ExportWeaponBooks()
    {
        var list = new List<WeaponBookExport>();
        string[] guids = AssetDatabase.FindAssets("t:WeaponBookData");

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            WeaponBookData book = AssetDatabase.LoadAssetAtPath<WeaponBookData>(path);
            if (book == null) continue;

            var weaponIds = new List<string>();
            if (book.weapons != null)
            {
                foreach (var w in book.weapons)
                {
                    if (w != null) weaponIds.Add(w.name);
                }
            }

            list.Add(new WeaponBookExport
            {
                bookId = book.bookId,
                weaponIds = weaponIds.ToArray(),
                upgradeLevels = book.upgradeLevels,
                upgradeStats = book.upgradeStats
            });
        }

        return list;
    }
}
