// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class OfflineRewardBindings
    {
        readonly ICloudCodeService k_Service;
        public OfflineRewardBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<OfflineReward.RewardResult> CheckOfflineReward(string playerId)
        {
            return await k_Service.CallModuleEndpointAsync<OfflineReward.RewardResult>(
                "OfflineReward",
                "CheckOfflineReward",
                new Dictionary<string, object>()
                {
                    {"playerId", playerId},
                });
        }
    }
}
