// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.OfflineReward
{
    public partial class RewardResult
    {
        public int Exp;
        public int gold;
        public int Dia;
        public int clover;

        [Preserve]
        public RewardResult ()
        {
        }
    }
}